name: meditrack
description: Um aplicativo para rastrear a ingestão de medicamentos

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0  # Versão compatível com firebase_auth
  firebase_auth: ^5.1.4  # Versão estável e compatível
  cloud_firestore: ^5.0.0
  provider: ^6.1.2
  flutter_local_notifications: ^14.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
